language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_74e343421d1f_key -iv $encrypted_74e343421d1f_iv
  -in .travis\/id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~\/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~\/.ssh/id_rsa
- cp .travis/ssh_config ~\/.ssh/config
- npm install -g hexo-cli
install:
- npm install
script:
- hexo generate
after_success:
- git config --global user.name "Peng:-)"
- git config --global user.email "liyp.yunpeng@gmail.com"
- hexo deploy
